package com.example.caloriecounter;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import java.lang.ref.SoftReference;

public class StatusAdapter extends AppCompatActivity {

    AutoCompleteTextView tvFood;

    public static final String[] FOOD = new String[]{
            "Cârnăciori picanți gatiți la tigaie",
            "Cârnați de casă gătiți la tigaie",
            "Carne porc tocată cântărită crudă",
            "Carne de vită gătită ",
            "Carne vită slabă cântărită crudă",
            "Ceafă de porc cântărită crudă",
            "Ceafă de porc cântărită crudă (grăsimea dată jos)",
            "Ceafă de porc cântărită gătită",
            "Ceafă de vită cântărită crudă",
            "Ciocanele de pui cântărite crude",
            "Coastă de porc crudă (fara grasime)",
            "Cotlet de porc la grătar",
            "Cotlet de porc cântărit crud",
            "Ficăței de pui cântăriți cruzi",
            "Ficăței de pui gătiți la tigaie (cu puțin ulei)",
            "Mici amestec vită și porc cântăriți cruzi",
            "Mușchiuleț de porc slab cântărit crud",
            "Piept de pui la grătar",
            "Piept de pui, fără piele cântărit crud",
            "Pipote și inimi de pui",
            "Pulpă porc crudă semi-grasă cântărită crudă",
            "Pulpe gatite cântătite cu os și piele",
            "Pulpe pui dezosate fără piele la grătar",
            "Pulpe pui la grătar cu piele cântărite fără os",
            "Pulpe pui la grătar fără piele (cântărite cu os)",
            "Puple pui, fără piele, crude",
            "Carne pentru modificat",
            "Șorici de porc",
            "Albuș de ou găină ",
            "Galbenuș de ou găină ",
            "Ouă găină",
            "Cabanos",
            "Crenvursti pui",
            "Crenvusti amestec",
            "Jambon",
            "Kaiser",
            "Muschi file de porc presat",
            "Muschi porc afumat",
            "Pastrama porc ",
            "Pastrama pui ",
            "Salam Banatean",
            "Salam de Sibiu",
            "Salam de vara ",
            "Salam Sasesc",
            "Slănină de porc",
            "Șuncă de Praga",
            "Șuncă de pui slabă (verifică eticheta)",
            "Șunculiță țărănească",
            "Brânză de vaci 0% grăsime",
            "Brânză de vaci 1% grasime",
            "Brânză de vaci 15% grăsime",
            "Brânză de vaci 3% grasime",
            "Brânză de vaci 8% grăsime",
            "Brânză de vaci țărănească",
            "Brânză Făgăraș",
            "Caș de vacă",
            "Cașcaval (in medie)",
            "Cașcaval 20%",
            "Felii/triunghiuri Brânză topită",
            "Mozzarella ",
            "Telemea de oaie",
            "Telemea vacă",
            "Urdă de oaie",
            "Urdă de vaca",
            "Iaurt 0.1%",
            "Iaurt 3.5%",
            "Lapte de vacă 0,1%",
            "Lapte de vacă 1,5%",
            "Lapte de vacă 3,5%",
            "Sana 0,1% ",
            "Sana 3,5%",
            "Smântână 20%",
            "Smântână 30%",
            "Cartofi fierți/copți",
            "Cartofi Dulci fierți/copți (cei copți sunt geniali)",
            "Cartofi prajiți ",
            "Cartofi țărănești",
            "Cartofi prăjiți Fast-Food ",
            "Corn Flakes porumb",
            "Crackers (un fel de felii de pâine foarte subțiri)",
            "Făină alba",
            "Făină de orez",
            "Făină malai",
            "Fasole albă cântărită crudă",
            "Fasole albă fiartă",
            "Fasole păstai",
            "Fulgi de orz",
            "Fulgi de ovăz",
            "Fulgi Secară",
            "Mamaligă (o parte făină, trei părți apă)",
            "Mazăre fiartă ",
            "Musli ",
            "Orez alb cântărit crud",
            "Orez alb fiert",
            "Orez brun cântărit crud",
            "Pâine albă ",
            "Pâine albă prăjită",
            "Pâine neagră",
            "Paine Vel Pitar",
            "Paste cu ou (e un sortiment)",
            "Paste de ovăz ",
            "Paste din orez",
            "Piure de cartofi",
            "Porumb dulce conservă",
            "Spaghetti / Macaroane/ Mecisori, etc. crude",
            "Spaghetti / Macaroane/ Mecisori, etc. fierte",
            "Spaghetti integrale",
            "Tabletă Glucoza",
            "Tartine din grâu (cea mai plictisitoare mâncare)",
            "Tartine din orez (cea mai plictisitoare mâncare)",
            "Tortellini sau Raviolini",
            "Fructe de pădure",
            "Ananas",
            "Avocado",
            "Banane ",
            "Caise ",
            "Căpșuni",
            "Cireșe",
            "Grapefruit",
            "Gutui",
            "Kiwi",
            "Mere (media)",
            "Pepene verde",
            "Pere",
            "Piersici",
            "Portocale",
            "Prune",
            "Rodie",
            "Struguri ",
            "Ardei gras",
            "Broccoli fiert",
            "Castraveți",
            "Ceapă",
            "Ciuperci",
            "Dovlecei ",
            "Legume Mexicane/Mix de legume congelate",
            "Legume in medie (le pui toate la grămadă aici)",
            "Măsline Kalamata",
            "Masline negre",
            "Măsline verzi murate",
            "Morcovi",
            "Roșii",
            "Sfecla roșie fiartă",
            "Soia ",
            "Spanac congelat ",
            "Spanac fiert (fără ulei, unt sau smântână)",
            "Spanac gătit cu puțină smântănă și unt",
            "Varză",
            "Vinete",
            "Alune crude",
            "Alune prăjite în ulei",
            "Fistic",
            "Migdale",
            "Nuci",
            "Semințe de dovleac în coajă",
            "Semințe de dovleac decojite",
            "Semințe floarea soarelui decojite",
            "Semințe floarea soarelui in coajă",
            "Biban Prăjit",
            "Caras gătit ",
            "Cod crud",
            "Crap crud",
            "Macrou afumat",
            "Pangasius crud",
            "Păstrăv crud",
            "Șalău crud",
            "Somn crud",
            "Somon crud",
            "Şprot afumat",
            "Maioneză de casă (in medie)",
            "Margarină",
            "Miere",
            "Salată de icre",
            "Slănină",
            "Ulei de in",
            "Ulei de masline",
            "Ulei floarea soarelui",
            "Unt 65%",
            "Unt 80%",
            "Zahăr Alb",
            "Zahăr Brun",
            "Batoane de proteine (în medie)",
            "Pudră de proteine (în medie)",
            "Castraveți murați în oțet",
            "Conservă de porc (în medie)",
            "Conservă Ananas",
            "Ketchup/Muștar",
            "Pate pasăre/porc/amestec (în medie)",
            "Sardine in sos tomat",
            "Sardine in ulei scurse",
            "Ton conserva in ulei",
            "Ton conserva suc propriu",
            "Ton in sos iute",
            "Zacuscă de fasole",
            "Zacuscă de vinete",
            "Aripioare picante KFC",
            "Baklava",
            "Batoane de ciocolată cu alune/cremă",
            "Baton cu Susan si Miere",
            "Biscuiți Dietetici",
            "Biscuiți Picnic",
            "Biscuiți umpluti",
            "Bomboane (în medie)",
            "Brezzels (covrigei mici)",
            "Cereale cu ciocolată",
            "Cheeseburger McDonalds ",
            "Ciocolată caldă cremă",
            "Ciocolată cu alune",
            "Ciocolată cu lapte",
            "Cipsuri cartofi prăjite în ulei",
            "Clătite cu ciocolată",
            "Clatite de casă (doar foi)",
            "Compot fructe (in medie)",
            "Corn cu ciocolată",
            "Corn simplu",
            "Covrig cu sare, mac sau susan",
            "Cozonac (în medie)",
            "Cremeș",
            "Crispy Strips KFC",
            "Dulceață de nuci",
            "Dulceață in medie",
            "Eugenie",
            "Finetti",
            "Înghețată Alpin",
            "Înghețată Betty Blue fructe padure ",
            "Înghețată Betty Ice Balleto (recomand Betty Ice)",
            "Înghețată Betty Ice Destiny ",
            "Înghețată Betty Ice Moana ",
            "Înghețată Betty Ice Vafa ",
            "Înghețată TopGel",
            "Kebab de pui",
            "Lapte cu ciocolată",
            "M&M's",
            "Papanași de casă cu dulceață",
            "Pizza cu ton",
            "Pizza de post",
            "Pizza diverse sortimente",
            "Pizza doar cu pui (in medie)",
            "Plăcintă cu brânză",
            "Plăcintă cu ciuperci",
            "Plăcintă cu dovleac",
            "Plăcintă cu mar",
            "Pop corn microunde",
            "Praf de budincă",
            "Prăjitură cu brânză de casă",
            "Prăjitură cu ciocolată",
            "Prăjituri de toate felurile (in medie)",
            "Salam de biscuiți",
            "Salatini",
            "Sticksuri (în medie)",
            "Shaorma piept de pui cu de toate",
            "Tiramisu",
            "Tort de ciocolată (în medie)",
            "Chiftele de porc",
            "Chiftele de pui",
            "Ciorbă de burtă",
            "Ciorbă de fasole",
            "Ciorbă de legume",
            "Ciorbă de perișoare",
            "Ciorbă de pui ",
            "Ciorbă de pui ala grec cu smântână",
            "Ciorbă de vacuță",
            "Cordon Bleu de pui",
            "Chilli con Carne ",
            "Drob de miel",
            "Iahnie de fasole cu ciolan",
            "Lasagna de porc",
            "Mâncare chinezească (pui cu orez)",
            "Paste Bolognese",
            "Paste Carbonara",
            "Salată de Boeuf",
            "Salată de Vinete",
            "Sarmale porc și vită",
            "Supă de pui",
            "Șnițel de pui",
            "Tocană carne porc/miel/vită",
            "Tocană de pui cu smantana/îngroșală",
            "Tocăniță de cartofi cu puțin ulei",
            "Bere blonda (medie)",
            "Bere fara alcool",
            "Coniac 40%",
            "Tuica (in medie)",
            "Vin rosu 10% alcool(medie)",
            "Vodka",
            "Whiskey"
    };

    public static final String[] CALORII = new String[]{
            "269.8",
            "314.1",
            "285.0",
            "194.0",
            "98.0",
            "203.0",
            "211.0",
            "261.2",
            "179.0",
            "149.0",
            "174.0",
            "203.0",
            "147.5",
            "113.0",
            "165.2",
            "294.0",
            "114.6",
            "146.0",
            "107.3",
            "109.6",
            "211.0",
            "151.3",
            "164.8",
            "232.3",
            "105.9",
            "125.5",
            "218.0",
            "570.4",
            "49.8",
            "323.0",
            "146.0",
            "315.4",
            "254.4",
            "290.4",
            "154.0",
            "402.0",
            "136.0",
            "111.0",
            "135.0",
            "129.0",
            "430.0",
            "479.2",
            "356.9",
            "328.0",
            "645.3",
            "130.1",
            "95.0",
            "276.0",
            "74.1",
            "85.0",
            "223.0",
            "103.0",
            "136.0",
            "314.0",
            "120.0",
            "252.4",
            "309.0",
            "280.0",
            "283.0",
            "260.0",
            "275.8",
            "235.0",
            "211.0",
            "144.0",
            "34.9",
            "61.9",
            "34.1",
            "50.8",
            "63.9",
            "17.7",
            "60.7",
            "203.6",
            "292.4",
            "90.2",
            "92.6",
            "204.0",
            "164.0",
            "288.3",
            "388.7",
            "378.5",
            "355.4",
            "308.0",
            "349.3",
            "317.0",
            "127.7",
            "88.0",
            "338.2",
            "375.0",
            "296.1",
            "109.8",
            "76.0",
            "343.0",
            "357.0",
            "126.3",
            "367.0",
            "255.8",
            "303.5",
            "243.6",
            "172.5",
            "388.0",
            "375.0",
            "344.8",
            "110.2",
            "101.2",
            "354.2",
            "141.7",
            "332.1",
            "310.8",
            "358.1",
            "366.9",
            "381.3",
            "42.3",
            "55.3",
            "174.3",
            "98.3",
            "54.0",
            "36.3",
            "68.0",
            "33.7",
            "62.5",
            "64.1",
            "53.2",
            "34.6",
            "64.5",
            "59.1",
            "51.7",
            "51.1",
            "91.6",
            "99.4",
            "28.8",
            "42.0",
            "18.1",
            "44.0",
            "24.3",
            "12.9",
            "47.0",
            "22.0",
            "293.5",
            "184.7",
            "156.9",
            "42.9",
            "21.0",
            "36.2",
            "321.8",
            "27.7",
            "29.9",
            "49.4",
            "28.9",
            "28.6",
            "610.4",
            "659.5",
            "602.0",
            "636.0",
            "701.0",
            "470.8",
            "565.0",
            "694.0",
            "344.0",
            "180.3",
            "102.0",
            "105.0",
            "121.6",
            "271.8",
            "88.0",
            "147.0",
            "85.0",
            "230.0",
            "200.0",
            "91.8",
            "536.4",
            "713.0",
            "330.8",
            "550.6",
            "572.0",
            "891.0",
            "828.0",
            "891.0",
            "589.0",
            "724.0",
            "400.0",
            "389.2",
            "410.3",
            "384.5",
            "11.2",
            "207.0",
            "88.0",
            "101.5",
            "178.3",
            "107.0",
            "201.9",
            "148.4",
            "85.0",
            "94.7",
            "145.0",
            "85.0",
            "321.4",
            "404.0",
            "508.8",
            "542.3",
            "413.7",
            "453.0",
            "487.0",
            "408.9",
            "414.4",
            "405.7",
            "262.5",
            "395.0",
            "553.4",
            "542.7",
            "537.0",
            "499.5",
            "201.4",
            "104.0",
            "442.3",
            "250.4",
            "373.2",
            "459.8",
            "186.7",
            "242.8",
            "564.6",
            "225.2",
            "347.8",
            "547.0",
            "232.6",
            "193.6",
            "181.6",
            "161.1",
            "125.6",
            "140.7",
            "300.7",
            "158.4",
            "67.1",
            "464.2",
            "262.0",
            "230.3",
            "278.0",
            "273.5",
            "229.0",
            "261.0",
            "205.1",
            "196.1",
            "215.5",
            "445.0",
            "324.8",
            "326.5",
            "496.2",
            "510.0",
            "194.8",
            "501.0",
            "392.0",
            "170.2",
            "247.5",
            "244.5",
            "170.0",
            "162.0",
            "137.4",
            "86.0",
            "31.5",
            "36.1",
            "98.7",
            "329.4",
            "82.2",
            "215.6",
            "141.5",
            "213.0",
            "110.7",
            "301.0",
            "208.5",
            "267.2",
            "186.2",
            "151.8",
            "107.8",
            "186.2",
            "83.0",
            "193.5",
            "344.0",
            "112.0",
            "106.0",
            "43.0",
            "17.0",
            "239.0",
            "250.0",
            "90.0",
            "231.0",
            "251.0"
    };

    public static final String[] PROTEINE = new String[]{
            "13.0",
            "18.0",
            "15.0",
            "26.0",
            "20.0",
            "17.0",
            "19.0",
            "22.1",
            "20.0",
            "17.0",
            "21.0",
            "26.0",
            "20.0",
            "17.0",
            "25.8",
            "15.0",
            "21.0",
            "27.5",
            "21.2",
            "15.7",
            "19.0",
            "15.1",
            "25.0",
            "23.2",
            "15.9",
            "19.0",
            "7.0",
            "63.4",
            "11.0",
            "16.0",
            "13.0",
            "12.6",
            "12.1",
            "12.1",
            "18.0",
            "15.0",
            "16.0",
            "21.0",
            "18.0",
            "16.0",
            "25.0",
            "24.2",
            "15.8",
            "17.0",
            "9.0",
            "16.0",
            "15.0",
            "13.0",
            "17.0",
            "17.0",
            "18.0",
            "17.0",
            "15.0",
            "17.0",
            "9.0",
            "24.3",
            "19.0",
            "20.0",
            "15.0",
            "19.0",
            "16.5",
            "16.0",
            "18.0",
            "18.0",
            "4.0",
            "3.6",
            "3.3",
            "3.2",
            "3.1",
            "3.2",
            "3.3",
            "2.9",
            "2.6",
            "2.0",
            "2.0",
            "4.0",
            "3.0",
            "4.2",
            "7.7",
            "9.5",
            "10.3",
            "7.0",
            "9.0",
            "22.0",
            "8.8",
            "4.0",
            "10.4",
            "13.0",
            "9.5",
            "3.0",
            "5.0",
            "9.0",
            "7.0",
            "2.7",
            "8.0",
            "7.1",
            "8.0",
            "8.5",
            "17.0",
            "13.0",
            "13.0",
            "5.6",
            "0.8",
            "2.9",
            "10.0",
            "4.0",
            "14.5",
            "0.0",
            "13.5",
            "9.0",
            "12.7",
            "0.7",
            "0.5",
            "2.0",
            "1.1",
            "1.4",
            "0.7",
            "1.0",
            "0.1",
            "0.4",
            "1.1",
            "0.3",
            "0.6",
            "0.4",
            "1.2",
            "0.9",
            "0.7",
            "1.5",
            "0.9",
            "1.0",
            "2.4",
            "0.7",
            "0.9",
            "2.3",
            "1.0",
            "3.0",
            "0.5",
            "0.0",
            "0.1",
            "1.0",
            "0.9",
            "0.9",
            "0.3",
            "50.0",
            "3.2",
            "3.0",
            "3.0",
            "1.4",
            "1.0",
            "25.8",
            "16.8",
            "21.0",
            "21.0",
            "15.0",
            "23.0",
            "27.0",
            "19.0",
            "10.0",
            "20.6",
            "21.0",
            "24.0",
            "17.8",
            "20.7",
            "13.0",
            "21.0",
            "19.0",
            "17.0",
            "22.1",
            "18.8",
            "10.0",
            "0.3",
            "0.3",
            "2.0",
            "8.0",
            "0.0",
            "0.0",
            "0.0",
            "1.0",
            "1.0",
            "0.0",
            "0.0",
            "22.5",
            "70.0",
            "0.5",
            "17.0",
            "0.0",
            "0.9",
            "11.0",
            "12.0",
            "24.6",
            "19.0",
            "19.0",
            "9.6",
            "5.0",
            "1.0",
            "20.3",
            "4.0",
            "9.2",
            "17.7",
            "10.7",
            "8.0",
            "6.2",
            "0.2",
            "10.8",
            "7.2",
            "13.0",
            "6.0",
            "6.6",
            "7.7",
            "5.5",
            "6.0",
            "6.8",
            "1.0",
            "6.7",
            "10.0",
            "7.8",
            "7.4",
            "5.3",
            "14.2",
            "8.6",
            "1.3",
            "6.7",
            "3.0",
            "3.3",
            "2.1",
            "3.5",
            "3.4",
            "2.6",
            "2.1",
            "4.4",
            "9.6",
            "3.4",
            "4.0",
            "9.0",
            "9.2",
            "7.0",
            "13.0",
            "14.0",
            "5.5",
            "3.9",
            "3.9",
            "6.0",
            "8.0",
            "4.7",
            "5.5",
            "6.0",
            "4.5",
            "5.2",
            "8.0",
            "9.0",
            "9.2",
            "4.7",
            "2.6",
            "14.0",
            "16.0",
            "13.0",
            "2.0",
            "0.3",
            "1.7",
            "4.3",
            "18.0",
            "4.4",
            "15.5",
            "10.0",
            "16.0",
            "6.0",
            "11.0",
            "9.0",
            "13.0",
            "7.6",
            "8.1",
            "1.0",
            "8.4",
            "4.0",
            "24.0",
            "15.0",
            "8.0",
            "2.0",
            "0.5",
            "0.3",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0"
    };

    public static final String[] GRASIMI = new String[]{
            "24.2",
            "26.9",
            "25.0",
            "10.0",
            "2.0",
            "15.0",
            "15.0",
            "19.2",
            "11.0",
            "9.0",
            "10.0",
            "11.0",
            "7.5",
            "5.0",
            "6.4",
            "26.0",
            "3.4",
            "4.0",
            "2.5",
            "5.2",
            "15.0",
            "10.1",
            "7.2",
            "15.5",
            "4.7",
            "5.5",
            "10.0",
            "35.2",
            "0.2",
            "27.0",
            "10.0",
            "29.0",
            "22.0",
            "26.0",
            "8.0",
            "38.0",
            "8.0",
            "3.0",
            "7.0",
            "5.0",
            "36.0",
            "41.6",
            "32.5",
            "28.0",
            "67.7",
            "6.5",
            "3.0",
            "24.0",
            "0.1",
            "1.0",
            "15.0",
            "3.0",
            "8.0",
            "26.0",
            "8.0",
            "16.0",
            "25.0",
            "20.0",
            "23.0",
            "20.0",
            "23.0",
            "19.0",
            "15.0",
            "8.0",
            "0.1",
            "3.5",
            "0.1",
            "2.0",
            "3.5",
            "0.1",
            "3.5",
            "20.0",
            "30.0",
            "0.2",
            "0.2",
            "12.0",
            "8.0",
            "15.5",
            "0.3",
            "4.5",
            "1.0",
            "0.0",
            "0.5",
            "1.0",
            "0.5",
            "0.0",
            "1.4",
            "7.0",
            "1.7",
            "0.2",
            "0.0",
            "3.0",
            "1.0",
            "0.3",
            "3.0",
            "3.0",
            "3.5",
            "0.8",
            "0.5",
            "4.0",
            "7.0",
            "0.0",
            "3.0",
            "1.2",
            "1.0",
            "0.4",
            "2.9",
            "0.0",
            "0.9",
            "2.1",
            "8.5",
            "0.7",
            "0.1",
            "14.7",
            "0.3",
            "0.4",
            "0.3",
            "0.0",
            "0.1",
            "0.1",
            "0.1",
            "0.0",
            "0.2",
            "0.1",
            "0.3",
            "0.1",
            "0.3",
            "1.2",
            "0.2",
            "0.0",
            "0.4",
            "0.1",
            "0.0",
            "0.3",
            "0.1",
            "0.2",
            "0.0",
            "26.7",
            "16.7",
            "15.3",
            "0.1",
            "0.2",
            "0.2",
            "0.2",
            "0.1",
            "0.3",
            "2.6",
            "0.1",
            "0.2",
            "49.2",
            "56.3",
            "46.0",
            "52.0",
            "65.0",
            "38.0",
            "45.0",
            "58.0",
            "28.0",
            "9.1",
            "2.0",
            "1.0",
            "5.6",
            "21.0",
            "4.0",
            "7.0",
            "1.0",
            "18.0",
            "12.4",
            "1.8",
            "54.0",
            "79.0",
            "0.0",
            "59.8",
            "60.0",
            "99.0",
            "92.0",
            "99.0",
            "65.0",
            "80.0",
            "0.0",
            "0.0",
            "11.1",
            "6.5",
            "0.0",
            "15.0",
            "0.0",
            "0.3",
            "13.9",
            "5.0",
            "11.5",
            "8.0",
            "1.0",
            "3.5",
            "5.0",
            "5.0",
            "21.8",
            "20.0",
            "28.0",
            "39.1",
            "8.5",
            "12.6",
            "21.0",
            "2.1",
            "2.8",
            "7.7",
            "10.5",
            "15.0",
            "35.0",
            "33.5",
            "35.0",
            "19.5",
            "8.6",
            "0.0",
            "27.5",
            "0.8",
            "6.0",
            "12.2",
            "8.3",
            "16.4",
            "37.4",
            "0.0",
            "9.0",
            "35.0",
            "8.6",
            "10.0",
            "6.0",
            "3.5",
            "4.0",
            "3.1",
            "12.3",
            "4.0",
            "1.5",
            "19.8",
            "18.0",
            "9.1",
            "10.0",
            "13.5",
            "9.0",
            "15.0",
            "5.5",
            "4.5",
            "3.5",
            "21.0",
            "2.0",
            "22.5",
            "24.2",
            "28.0",
            "14.0",
            "25.0",
            "8.0",
            "7.8",
            "10.7",
            "10.5",
            "10.0",
            "8.0",
            "8.6",
            "2.0",
            "1.5",
            "2.1",
            "7.9",
            "25.0",
            "5.4",
            "11.6",
            "5.5",
            "13.0",
            "4.7",
            "13.0",
            "8.5",
            "8.8",
            "7.4",
            "9.0",
            "9.0",
            "12.2",
            "3.0",
            "9.5",
            "30.0",
            "8.0",
            "2.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0"

    };

    public static final String[] CARBS = new String[]{
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "1.1",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "25.0",
            "0.0",
            "1.0",
            "4.0",
            "1.0",
            "1.0",
            "2.0",
            "2.0",
            "2.5",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "5.0",
            "1.5",
            "2.0",
            "0.3",
            "2.0",
            "0.0",
            "1.9",
            "2.0",
            "2.0",
            "1.3",
            "2.0",
            "4.0",
            "2.0",
            "1.0",
            "3.0",
            "3.0",
            "2.8",
            "2.0",
            "5.0",
            "4.0",
            "1.0",
            "0.7",
            "0.0",
            "1.0",
            "0.0",
            "4.5",
            "4.0",
            "5.0",
            "5.0",
            "5.0",
            "1.0",
            "4.0",
            "3.0",
            "3.0",
            "20.1",
            "20.7",
            "20.0",
            "20.0",
            "33.0",
            "88.8",
            "75.0",
            "76.3",
            "70.0",
            "77.2",
            "55.0",
            "22.0",
            "18.0",
            "71.0",
            "65.0",
            "60.7",
            "24.0",
            "14.0",
            "70.0",
            "80.0",
            "28.2",
            "77.0",
            "50.1",
            "60.0",
            "50.6",
            "25.0",
            "75.0",
            "65.0",
            "80.6",
            "20.0",
            "19.7",
            "76.3",
            "30.5",
            "62.0",
            "77.7",
            "74.0",
            "78.0",
            "63.5",
            "8.3",
            "13.1",
            "8.5",
            "22.8",
            "11.2",
            "7.7",
            "16.0",
            "8.1",
            "15.0",
            "14.7",
            "13.0",
            "7.6",
            "15.5",
            "12.9",
            "11.8",
            "11.4",
            "18.7",
            "23.5",
            "6.2",
            "7.2",
            "3.6",
            "10.1",
            "3.1",
            "2.0",
            "8.3",
            "5.0",
            "13.3",
            "8.5",
            "3.8",
            "9.6",
            "3.9",
            "8.3",
            "30.0",
            "3.5",
            "3.8",
            "3.5",
            "5.6",
            "5.7",
            "16.1",
            "21.4",
            "26.0",
            "21.0",
            "14.0",
            "9.2",
            "13.0",
            "24.0",
            "13.0",
            "4.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.1",
            "2.6",
            "0.2",
            "82.4",
            "1.1",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "100.0",
            "97.3",
            "55.1",
            "11.5",
            "2.3",
            "1.0",
            "22.0",
            "23.8",
            "2.3",
            "3.5",
            "0.0",
            "0.1",
            "0.0",
            "6.2",
            "20.0",
            "9.0",
            "11.0",
            "52.0",
            "55.0",
            "29.9",
            "73.6",
            "76.9",
            "68.3",
            "97.3",
            "86.5",
            "76.9",
            "29.0",
            "59.0",
            "53.0",
            "52.6",
            "50.0",
            "75.0",
            "24.2",
            "25.0",
            "42.0",
            "50.8",
            "72.0",
            "80.1",
            "22.7",
            "9.6",
            "48.4",
            "55.0",
            "60.0",
            "55.0",
            "35.5",
            "23.8",
            "28.4",
            "29.0",
            "19.8",
            "26.1",
            "43.1",
            "21.0",
            "10.0",
            "67.5",
            "16.0",
            "27.9",
            "40.0",
            "25.0",
            "23.0",
            "26.0",
            "35.0",
            "35.0",
            "40.0",
            "56.0",
            "72.0",
            "25.5",
            "63.6",
            "60.0",
            "12.0",
            "61.0",
            "71.0",
            "15.8",
            "33.1",
            "34.9",
            "6.0",
            "6.5",
            "2.0",
            "15.0",
            "4.2",
            "2.6",
            "2.6",
            "8.1",
            "4.0",
            "12.3",
            "13.0",
            "8.0",
            "11.1",
            "35.0",
            "24.0",
            "34.0",
            "22.3",
            "9.6",
            "5.7",
            "10.7",
            "10.0",
            "3.0",
            "3.5",
            "2.0",
            "20.0",
            "3.5",
            "3.6",
            "0.1",
            "0.0",
            "3.7",
            "0.0",
            "0.0"
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_status_adapter);

        tvFood = findViewById(R.id.tvFood);

        ArrayAdapter<String> adapter = new ArrayAdapter<>(StatusAdapter.this, android.R.layout.simple_list_item_1, FOOD);
        tvFood.setAdapter(adapter);


        Toast.makeText(this, FOOD.length + " " + CALORII.length + " " +PROTEINE.length+ "  " + GRASIMI.length+ "  " + CARBS.length, Toast.LENGTH_SHORT).show();




    }
}
